export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_IS_LOADING = 'SET_IS_LOADING';

export const SET_GEOCACHES = 'SET_GEOCACHES';
export const CLEAR_GEOCACHES = 'CLEAR_GEOCACHES';
export const SET_FIELDNOTES = 'SET_FIELDNOTES';
export const CLEAR_FIELDNOTES = 'CLEAR_FIELDNOTES';